name: dl
channels:
  - defaults
  - pytorch
  - plotly
dependencies:
  - python=3.8
  - jupyter
  - scipy
  - pip
  - notebook
  - python-lmdb
  - plotly
  - pytorch=1.11
  - torchvision
  - cudatoolkit=11.3
  - pip:
    - hydra-core==1.1.1
