##

# baseline
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=1000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=2000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=3000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=6000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=12000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=18000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=24000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=36000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=48000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=64000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=72000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=84000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=96000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=112000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=128000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=144000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=152000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=160000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=168000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=174000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=176000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=180000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=184000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=188000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=192000

python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=1000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=2000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=3000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=6000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=12000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=18000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=24000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=36000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=48000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=64000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=72000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=84000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=96000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=112000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=128000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=144000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=152000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=160000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=168000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=174000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=176000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=180000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=184000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=188000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=192000

python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=1000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=2000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=3000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=6000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=12000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=18000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=24000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=36000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=48000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=64000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=72000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=84000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=96000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=112000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=128000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=144000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=152000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=160000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=168000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=174000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=176000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=180000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=184000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=188000
python train_sgd_variant.py name=sgd_noaug hyp=base_da data=CINIC10 model=resnet18 data.size=192000
